# render.yaml - Configuração segura
services:
  - type: web
    name: nutri-api-engine
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --workers 2 --threads 4"
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_ENV
        value: "production"
      - key: NUTRI_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://chat.openai.com,https://chatgpt.com"
