# Versão corrigida conforme auditoria de segurança.
# A variável X_API_KEY foi modificada para ser carregada a partir dos "Secrets" do ambiente Render,
# eliminando a exposição de credenciais no código-fonte.

services:
  - type: web
    name: pedro-barros-nutrition
    env: python
    region: oregon 
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: X_API_KEY
        fromSecret: true # CORREÇÃO: Carrega o valor da variável de ambiente segura (Secret)
