services:
  - type: web
    name: nutri-api-service
    env: python
    region: oregon 
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: X_API_KEY
        fromSecret: true
