# render.yaml
services:
  - type: web
    name: nutri-api-engine
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: NUTRI_API_KEY
        value: "chave_secreta_para_acessar_api"
